# Generated by Django 5.1.7 on 2025-03-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.IntegerField(blank=True, max_length=14, null=True),
        ),
    ]
