# Generated by Django 5.1.7 on 2025-03-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_clientes_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
